# -*- coding: utf-8 -*-
"""face model .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122z9VsiGg_CZYq2v37VV4IgxPACpVgUL
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

!cp "/content/drive/MyDrive/projects/unified ai/face_dataset.zip" .

!ls

!unzip face_dataset.zip

!ls

!ls UTKFace

!ls UTKFace/UTKFace | head

!mkdir raw_faces

!ls UTKFace/UTKFace | wc -l

!ls raw_faces | wc -l

!mv UTKFace/UTKFace/*.jpg raw_faces/

!ls raw_faces | wc -l

!ls UTKFace/UTKFace | wc -l

!rm -rf UTKFace

!ls

!mkdir -p face_dataset/normal

!mkdir -p face_dataset/risk

from IPython.core import display_trap
import os
import shutil

source_dir='raw_faces'
normal_dir='face_dataset/normal'
risk_dir='face_dataset/risk'

for img in os.listdir(source_dir):
    try:
        age=int(img.split('_')[0])
        src=os.path.join(source_dir,img)

        if age < 40 :
            dst=os.path.join(normal_dir,img)
        else:
            dst=os.path.join(risk_dir,img)
        shutil.move(src,dst)
    except:
        pass

print("Normal:", len(os.listdir("face_dataset/normal")))
print("Risk:", len(os.listdir("face_dataset/risk")))

from re import sub
from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen=ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_data=datagen.flow_from_directory(
    'face_dataset',
    target_size=(224,224),
    batch_size=32,
    class_mode='binary',
    subset='training'
)

val_data=datagen.flow_from_directory(
    'face_dataset',
    target_size=(224,224),
    batch_size=32,
    class_mode='binary',
    subset='validation'
)

from tensorflow.keras.applications import MobileNetV2

base_model=MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable=False

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D

face_model=Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(128,activation='relu'),
    Dense(1,activation='sigmoid')
])

face_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

face_model.summary()

history=face_model.fit(
    train_data,
    validation_data=val_data,
    epochs=5
)

face_model.save('face_cnn_model.h5')

face_model.save('face_cnn_model.keras')

from google.colab import files
files.download('face_cnn_model.h5')
files.download('face_cnn_model.keras')

import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np

model = tf.keras.models.load_model("face_cnn_model.keras")

import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np

model = tf.keras.models.load_model("face_cnn_model.h5")

img_path = input("Enter image path: ")

img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img)
img_array = img_array/255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)

print("Prediction score:", prediction[0][0])

if prediction[0][0] > 0.5:
    print("Result: Risk")
else:
    print("Result: Normal")

import matplotlib.pyplot as plt

plt.imshow(img)
plt.axis("off")
plt.show()

