# -*- coding: utf-8 -*-
"""integration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7M3r9jwgSK0FCSQ5sEZbeU9uLQXg4yL
"""

from keras.models import load_model
import numpy as np
import tensorflow as tf
import pickle
import joblib
from tensorflow.keras.preprocessing import image

def get_lab_input():
    data = {}

    print("\nEnter Lab Details:\n")

    for col in columns:

        if col == "BMI":
            continue

        while True:
            try:
                val = float(input(f"{col}: "))
                data[col] = val
                break
            except:
                print("Invalid input, try again")

    # BMI calculation
    while True:
        try:
            weight = float(input("Weight (kg): "))
            height = float(input("Height (cm): "))
            bmi = weight / ((height/100)**2)
            break
        except:
            print("Invalid weight/height")

    data["BMI"] = bmi

    lab_input = [data[col] for col in columns]

    return lab_input

data = joblib.load("lab_model.pkl")

lab_models = data["models"]
le_dict = data["label_encoders"]
columns = data["columns"]

print(type(lab_models))
print(len(lab_models))

try:
    nlp_model = pickle.load(open("nlp_model.pkl", "rb"))
except:
    nlp_model = joblib.load("nlp_model.pkl")

print(type(nlp_model))

medical_model = tf.keras.models.load_model("medical_model.keras",compile=False)

medical_model.summary()

print(nlp_model.keys())

vectorizer = nlp_model["vectorizer"]
nlp_model = nlp_model["model"]

# NLP
def predict_text(text):
    text_vec = vectorizer.transform([text.lower()])
    prob = nlp_model.predict_proba(text_vec)[0][1]
    return float(prob)


# LAB
def predict_lab(input_data):
    results = {}
    for disease, model in lab_models.items():
        prob = model.predict_proba([input_data])[0][1]
        results[disease] = float(prob)
    return results


# IMAGE
classes = ["skin_cancer", "kidney", "normal"]

def predict_medical_image(img_path):
    img = image.load_img(img_path, target_size=(224,224))
    img = image.img_to_array(img) / 255.0
    img = np.expand_dims(img, axis=0)

    preds = medical_model.predict(img)[0]
    return dict(zip(classes, preds))

print(len(columns))
print(columns)

data = {col: 0 for col in columns}
print(data)

data["BMI"] = 22
data["SleepTime"] = 7

lab_input = [data[col] for col in columns]
print(lab_input)

score, risk, lab_results = final_prediction(
    text="chest pain and dizziness",
    lab_input=lab_input,
    image_path=None
)

print(score)
print(risk)
print(lab_results)

face_model = tf.keras.models.load_model("face_cnn_model.h5", compile=False)

def predict_face(img_path):

    img = image.load_img(img_path, target_size=(224,224))
    img = image.img_to_array(img) / 255.0
    img = np.expand_dims(img, axis=0)

    prob = face_model.predict(img)[0][0]

    return float(prob)

def final_prediction(face_path, text, lab_input, image_path=None):

    probs = []

    # FACE
    try:
        probs.append(predict_face(face_path))
    except:
        print("Face error")

    # NLP
    probs.append(predict_text(text))

    # LAB
    lab_results = predict_lab(lab_input)
    probs.append(np.mean(list(lab_results.values())))

    # IMAGE
    if image_path:
        img_results = predict_medical_image(image_path)
        probs.append(img_results.get("skin_cancer", 0) + img_results.get("kidney", 0))

    final_score = sum(probs) / len(probs)

    if final_score >= 0.7:
        risk = "High Risk"
    elif final_score >= 0.4:
        risk = "Moderate Risk"
    else:
        risk = "Low Risk"

    return final_score, risk, lab_results

def age_to_category(age):
    if age <= 24: return "18-24"
    elif age <= 29: return "25-29"
    elif age <= 34: return "30-34"
    elif age <= 39: return "35-39"
    elif age <= 44: return "40-44"
    elif age <= 49: return "45-49"
    elif age <= 54: return "50-54"
    elif age <= 59: return "55-59"
    elif age <= 64: return "60-64"
    elif age <= 69: return "65-69"
    elif age <= 74: return "70-74"
    elif age <= 79: return "75-79"
    else: return "80+"

def get_lab_input():
    data = {}

    print("\nEnter Lab Details:\n")

    for col in columns:

        if col == "BMI":
            continue

        # 🔥 HANDLE AGE SEPARATELY
        if col == "AgeCategory":
            while True:
                try:
                    age = int(input("Age: "))
                    category = age_to_category(age)

                    # encode using label encoder
                    val = le_dict[col].transform([category])[0]

                    data[col] = val
                    break
                except:
                    print("Invalid age, try again")
            continue

        while True:
            try:
                val = input(f"{col}: ").strip().lower()

                # YES/NO
                if val in ["yes", "y"]:
                    val = 1
                elif val in ["no", "n"]:
                    val = 0

                # MALE/FEMALE
                elif val in ["male", "m"]:
                    val = 1
                elif val in ["female", "f"]:
                    val = 0

                else:
                    val = float(val)

                data[col] = val
                break

            except:
                print("Invalid input (use yes/no or number)")

    # BMI
    while True:
        try:
            weight = float(input("Weight (kg): "))
            height = float(input("Height (cm): "))
            bmi = weight / ((height/100)**2)
            break
        except:
            print("Invalid weight/height")

    data["BMI"] = bmi

    lab_input = [data[col] for col in columns]

    return lab_input

import matplotlib.pyplot as plt

def get_advice(risk):
    if risk == "High Risk":
        return "Immediate medical consultation recommended."
    elif risk == "Moderate Risk":
        return "Take precautions and monitor your health."
    else:
        return "You are in a safe range. Maintain a healthy lifestyle."


def plot_lab_results(lab_results):

    sorted_results = dict(sorted(lab_results.items(), key=lambda x: x[1], reverse=True))

    diseases = list(sorted_results.keys())
    probs = list(sorted_results.values())

    plt.figure()

    # horizontal bars
    plt.barh(diseases, probs)

    # highest on top
    plt.gca().invert_yaxis()

    # ❌ REMOVE ONLY X-AXIS
    plt.xticks([])

    # ✅ KEEP Y-AXIS (disease names)
    plt.yticks(range(len(diseases)), diseases)

    # add values on bars
    for i, v in enumerate(probs):
        plt.text(v, i, f"{v:.2f}", va='center')

    plt.title("Disease Risk")
    plt.box(False)
    plt.show()

# ===== RUN PROGRAM =====

face_path = input("Enter face image path: ")
medical_path = input("Enter medical image path: ")
text = input("Enter symptoms: ")

lab_input = get_lab_input()

score, risk, lab_results = final_prediction(
    face_path=face_path,
    text=text,
    lab_input=lab_input,
    image_path=medical_path
)

print("\n===== FINAL RESULT =====")
print("Risk:", risk)

advice = get_advice(risk)
print("Advice:", advice)

plot_lab_results(lab_results)

