# -*- coding: utf-8 -*-
"""Lab data model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15uK2Z7G0FkPLElfD8K7g2woc7Kyxp0Gl
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("/content/Heart_new2.csv")

drop_cols = ["Race", "MentalHealth", "PhysicalHealth", "GenHealth"]

df = df.drop(columns=drop_cols, errors='ignore')

le_dict = {}

for col in df.columns:
    if df[col].dtype == 'object':
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        le_dict[col] = le

diseases = ["HeartDisease","Stroke","KidneyDisease","SkinCancer","Asthma","Diabetic"]

X = df.drop(diseases, axis=1)

models = {}

for disease in diseases:
    y = df[disease]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestClassifier()
    model.fit(X_train, y_train)

    models[disease] = model

def calculate_bmi(weight, height_cm):
    height_m = height_cm / 100
    return weight / (height_m ** 2)

def age_to_category(age):
    if age <= 24: return "18-24"
    elif age <= 29: return "25-29"
    elif age <= 34: return "30-34"
    elif age <= 39: return "35-39"
    elif age <= 44: return "40-44"
    elif age <= 49: return "45-49"
    elif age <= 54: return "50-54"
    elif age <= 59: return "55-59"
    elif age <= 64: return "60-64"
    elif age <= 69: return "65-69"
    elif age <= 74: return "70-74"
    elif age <= 79: return "75-79"
    else: return "80+"

def get_user_input():

    data = {}

    print("\nEnter Details (type 'exit' anytime to stop)\n")

    for col in X.columns:

        # 🚫 SKIP BMI (we calculate)
        if col == "BMI":
            continue

        while True:
            try:
                if col == "AgeCategory":
                    val = input("Enter Age: ")
                else:
                    val = input(f"{col}: ")

                if val.lower() == "exit":
                    return None

                # AGE → convert
                if col == "AgeCategory":
                    age = int(val)
                    category = age_to_category(age)
                    val = le_dict[col].transform([category])[0]

                # CATEGORICAL
                elif col in le_dict:
                    options = list(le_dict[col].classes_)

                    if val not in options:
                        print(f"❌ Choose from {options}")
                        continue

                    val = le_dict[col].transform([val])[0]

                # NUMERIC
                else:
                    val = float(val)

                data[col] = val
                break

            except:
                print("❌ Invalid input, try again!")

    # 🔥 NOW ADD BMI
    while True:
        try:
            weight = float(input("Weight (kg): "))
            height = float(input("Height (cm): "))
            bmi = calculate_bmi(weight, height)
            break
        except:
            print("❌ Invalid weight/height")

    # Insert BMI in correct position
    data["BMI"] = bmi

    # Ensure order
    ordered_data = [data[col] for col in X.columns]

    return np.array(ordered_data)

def predict_and_plot(input_data):

    if input_data is None:
        print("Exited.")
        return

    results = {}

    for disease, model in models.items():
        prob = model.predict_proba([input_data])[0][1]
        results[disease] = prob

    print("\nDisease Probabilities:")
    for k, v in results.items():

        if v >= 0.7:
            level = "High Risk"
        elif v >= 0.4:
            level = "Moderate Risk"
        else:
            level = "Low Risk"

        print(f"{k}: {level} ({v:.2f})")

    # 🔥 SORT
    sorted_results = dict(sorted(results.items(), key=lambda x: x[1], reverse=True))

    diseases = list(sorted_results.keys())
    probs = list(sorted_results.values())

    # 🔥 HORIZONTAL BAR
    plt.figure()

    plt.barh(diseases, probs)

    plt.gca().invert_yaxis()

    # ❌ remove x-axis
    plt.xticks([])

    # add labels on bars instead
    for i, v in enumerate(probs):
        plt.text(v, i, f"{v:.2f}", va='center')

    plt.title("Disease Prediction")
    plt.show()

    return sorted_results

user_data = get_user_input()
predict_and_plot(user_data)

