# -*- coding: utf-8 -*-
"""Medical image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IbW8xaE_IZosvfcwm59uDQ89QNVrqVQG
"""

import json

kaggle_dict = {
    "username": "chintu's work",
    "key": "KGAT_0dbca83dff4e6e0c88def4c752abc6d2"
}

with open("kaggle.json", "w") as f:
    json.dump(kaggle_dict, f)

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets list

!kaggle datasets download -d kmader/skin-cancer-mnist-ham10000

!unzip skin-cancer-mnist-ham10000.zip -d skin_data

!kaggle datasets download -d nazmul0087/ct-kidney-dataset-normal-cyst-tumor-and-stone

!unzip ct-kidney-dataset-normal-cyst-tumor-and-stone.zip -d kidney_data

!mkdir -p medical_data/skin_cancer
!mkdir -p medical_data/kidney
!mkdir -p medical_data/normal

!cp skin_data/HAM10000_images_part_1/* medical_data/skin_cancer/
!cp skin_data/HAM10000_images_part_2/* medical_data/skin_cancer/

!ls medical_data/skin_cancer | tail -n +3001 | xargs -I {} rm medical_data/skin_cancer/{}

!cp kidney_data/*/*/Cyst/* medical_data/kidney/
!cp kidney_data/*/*/Tumor/* medical_data/kidney/
!cp kidney_data/*/*/Stone/* medical_data/kidney/
!cp kidney_data/*/*/Normal/* medical_data/normal/

!ls medical_data
!ls medical_data/skin_cancer | wc -l
!ls medical_data/kidney | wc -l
!ls medical_data/normal | wc -l

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models
import numpy as np
from tensorflow.keras.preprocessing import image

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_data = datagen.flow_from_directory(
    "medical_data/",
    target_size=(224,224),
    batch_size=16,
    class_mode='categorical',
    subset='training'
)

val_data = datagen.flow_from_directory(
    "medical_data/",
    target_size=(224,224),
    batch_size=16,
    class_mode='categorical',
    subset='validation'
)

print(train_data.class_indices)

base = MobileNetV2(
    input_shape=(224,224,3),
    include_top=False,
    weights='imagenet'
)

base.trainable = False

model = models.Sequential([
    base,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=1
)

def predict_uploaded_image():

    from google.colab import files
    uploaded = files.upload()

    img_path = list(uploaded.keys())[0]

    img = image.load_img(img_path, target_size=(224,224))
    img = image.img_to_array(img) / 255.0
    img = np.expand_dims(img, axis=0)

    preds = model.predict(img)[0]

    classes = list(train_data.class_indices.keys())
    results = dict(zip(classes, preds))

    print("\nPrediction:")
    for k, v in results.items():
        print(f"{k}: {v:.2f}")

    return results

result = predict_uploaded_image()

print("\nFinal Risk Score:")
print(result["skin_cancer"] + result["kidney"])

risk_score = result["skin_cancer"] + result["kidney"]

if risk_score > 0.6:
    print(" High Risk")
elif risk_score > 0.3:
    print(" Medium Risk")
else:
    print(" Low Risk")

model.save("medical_model.keras")

